[package]
name = "embed_rust"
version = "0.1.0"
authors = ["spartazhihu <lun.wang@pku.edu.cn>"]

[lib]
name = "embed_rust"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
sgx_tstd = { git = "https://github.com/sunblaze-optio/rust-sgx-sdk" }
